### ISSUE TITLE
Install Anaconda on ipad

### ISSUE THREAD

**Issue by seataka** [pyjug/pythonjp-miyadaiku#66]
Install Anaconda on ipad

I'm an iPad beginner. in trouble

For studying AI
I downloaded and tried to install Anaconda on iPad PRO 10 inch (12.1.4) and I got a pkg file, but I tried various ways to start the installation

But I do not know.

I kindly thank you

<Selected as download destination>
https://www.anaconda.com/distribution/
iOS
Python 3.7 version
64-bit graphical installer (652.7 MB)

iPad初心者です。困っています

AIの勉強のため
iPad PRO 10インチ(12.1.4)にて、Anacondaをインストールしようとダウンロードしpkgファイルは入手したのですが、インストールの開始の仕方が、色々やってみたり調べたの

ですがわかりません。

何卒宜しくお願い致します

＜ダウンロード先と選択したもの＞
https://www.anaconda.com/distribution/
iOS
Python 3.7バージョン
64ビットグラフィカルインストーラ（652.7 MB）

**Comment by atsuoishimoto** [comment]
こちらはpython.jpの運営用リポジトリで、質問などへの対応は行っておりません。

Discordチャット https://www.python.jp/pages/pythonjp_discord.html や メーリングリスト 
https://groups.google.com/forum/#!forum/python-ml-jp などをご利用ください。

なお、AnacondaなどはiPadでは動きません。別途PCなどが必要となります。
